services:
  - type: web
    name: dansk-supervisor-github-api
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: GITHUB_TOKEN
        sync: false
      - key: GITHUB_OWNER
        value: KOlsen14
      - key: GITHUB_REPO
        value: Dansk-Supervisor-2.2
      - key: GITHUB_BRANCH
        value: main
      - key: ACTION_API_KEY
        generateValue: true
